version: '3'
services:
  tekactool:
    container_name: tekactool
    hostname: tekactool
    restart: always
    build: ./
    volumes:
      - ./:/app
    environment:
      - PYTHONBUFFERED=1
    ports:
      - "5001:5001"
  ofelia:
      image: mcuadros/ofelia:latest
      depends_on:
        - tekactool
        - parser
      command: daemon --docker
      restart: always
      volumes:
        - ./:/app
        - /var/run/docker.sock:/var/run/docker.sock:ro
      labels:
        ofelia.job-run.datecron.image: "parser"
        ofelia.job-run.datecron.schedule: "@every 5s"
        ofelia.job-run.datecron.command: "python3 /app/core/cron/Cron.py"
  parser:
    image: parser
    build: .
