apiVersion: v1
kind: Service
metadata:
  name: act-site-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: tekactool
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001

  selector:
    app: tekactool
  sessionAffinity: None

